import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NAVER',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
      <link rel='icon' href='/src/app/favicon.ico'/>
      <meta name="theme-color" content="#125082"/>
      <meta name="apple-mobile-web-app-status-bar-style" content="#125082"/>
    </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
